Repository parw8649/CST438-Project3, pull requests merged in 2021-12, with the labels that each got.

#67 Split profile views
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/DataClsAdapter.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/ViewHolders/DataClsVH.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/ViewHolders/EventVH.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/ViewHolders/GameVH.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/ViewHolders/PostVH.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/ViewHolders/RelationshipVH/UserToUserVH.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/DataClsVM.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/AddEventFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/EventsFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/GameCollectionFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/HomePostFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/HostedGamesFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/ProfileFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/UserFriendsFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/UserGamesFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/UserProfileFragment.java
  Android/app/src/main/res/layout/fragment_user_friends.xml
  Android/app/src/main/res/layout/fragment_user_profile.xml
  Android/app/src/main/res/layout/user_item.xml
  Android/app/src/main/res/navigation/nav_main_app.xml
  Android/app/src/main/res/values/strings.xml
Labels: Frontend

#75 Db updates
  Backend/Backend/urls.py
  Backend/BoardGameSocialAPI/admin.py
  Backend/BoardGameSocialAPI/models.py
  Backend/BoardGameSocialAPI/serializer.py
  Backend/BoardGameSocialAPI/views.py
  backend/BoardGameSocialAPI/fixtures/data.json
  backend/BoardGameSocialAPI/migrations/0001_initial.py
  backend/BoardGameSocialAPI/migrations/0002_auto_20211206_1453.py
  backend/BoardGameSocialAPI/migrations/0003_auto_20211206_1513.py
Labels: Backend

#77 Partial Search Page
  Android/app/build.gradle
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/java/com/example/boardgamesocial/API/RetrofitClient.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/DataClsAdapter.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/ViewHolders/DataClsVH.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/ViewHolders/GameVH.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/DataClsVM.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/SearchFragment.java
  Android/app/src/main/res/layout/fragment_search.xml
  Android/app/src/main/res/layout/search_game_item.xml
  Android/app/src/main/res/navigation/nav_main_app.xml
  Android/app/src/main/res/values/strings.xml
  Android/app/src/test/java/com/example/boardgamesocial/APITests/RequestChainTests.java
Labels: Frontend

#76 Updated with test and new call
  README.md
Labels: documentation

#78 Edit profile fragment
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/java/com/example/boardgamesocial/Commons/Constants.java
  Android/app/src/main/java/com/example/boardgamesocial/Commons/Utils.java
  Android/app/src/main/java/com/example/boardgamesocial/LoginAndSignUp/Fragments/LoginFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/AddPostFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/EditProfileFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/HomePostFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/ProfileFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/MainAppActivity.java
  Android/app/src/main/res/layout/activity_main_app.xml
  Android/app/src/main/res/layout/fragment_add_post.xml
  Android/app/src/main/res/layout/fragment_edit_profile.xml
  Android/app/src/main/res/layout/popup_window.xml
  Android/app/src/main/res/menu/navbar_options.xml
  Android/app/src/main/res/values/dimens.xml
  Android/app/src/main/res/values/strings.xml
Labels: bug, Frontend

#79 Profile DataClass and bug fixes
  Android/app/src/main/java/com/example/boardgamesocial/API/API.java
  Android/app/src/main/java/com/example/boardgamesocial/API/RetrofitClient.java
  Android/app/src/main/java/com/example/boardgamesocial/DataClasses/Profile.java
  Android/app/src/main/java/com/example/boardgamesocial/LoginAndSignUp/Fragments/LoginFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/GameCollectionFragment.java
  Backend/BoardGameSocialAPI/serializer.py
Labels: bug, Frontend

#80 Search Page
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/DataClsAdapter.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/ViewHolders/UserVH.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/SearchFragment.java
  Android/app/src/main/res/layout/fragment_search.xml
  Android/app/src/main/res/navigation/nav_main_app.xml
Labels: Frontend

#81 Updates
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/DataClsVM.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/EventAttendeesFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/EventsFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/GameCollectionFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/GameReviewsFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/UserGamesFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/MainAppActivity.java
  Android/app/src/main/res/layout/fragment_add_game_review.xml
  Android/app/src/main/res/layout/fragment_event_attendees.xml
  Android/app/src/main/res/layout/fragment_events.xml
  Android/app/src/main/res/layout/fragment_game_collection.xml
  Android/app/src/main/res/layout/fragment_game_reviews.xml
  Android/app/src/main/res/layout/fragment_hosted_games.xml
  Android/app/src/main/res/layout/fragment_single_event.xml
  Android/app/src/main/res/layout/fragment_single_hosted_game.xml
  Android/app/src/main/res/layout/fragment_user_games.xml
Labels: Frontend
