Repository parw8649/CST438-Project3, pull requests merged in 2021-11, with the labels that each got.

#36 Preview changes for layouts
  Android/app/src/main/res/layout/activity_main.xml
  Android/app/src/main/res/layout/activity_sign_up.xml
  Android/app/src/main/res/values/dimens.xml
Labels: Frontend

#38 main <- Home page and nav bar
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/java/com/example/boardgamesocial/HomePostActivity.java
  Android/app/src/main/res/drawable/ic_baseline_add_24.xml
  Android/app/src/main/res/drawable/ic_baseline_more_vert_24.xml
  Android/app/src/main/res/drawable/ic_baseline_search_24.xml
  Android/app/src/main/res/layout/activity_home_post.xml
  Android/app/src/main/res/layout/item.xml
  Android/app/src/main/res/layout/nav_bar.xml
  Android/app/src/main/res/menu/navbar_options.xml
  Android/app/src/main/res/values/colors.xml
  Android/app/src/main/res/values/strings.xml
  Android/app/src/main/res/values/themes.xml
Labels: Frontend

#40 Manual Docker Update
  Backend/requirements.txt
  backend/Dockerfile
  backend/docker-compose.yml
Labels: DevOps

#41 Fixed InvocationTargetException
  Android/app/src/main/res/layout/activity_main.xml
  Android/app/src/main/res/layout/activity_sign_up.xml
Labels: bug

#42 Games collection
  Android/app/src/main/java/com/example/boardgamesocial/GamesCollectionActivity.java
  Android/app/src/main/java/com/example/boardgamesocial/HomePostActivity.java
  Android/app/src/main/java/com/example/boardgamesocial/MainActivity.java
  Android/app/src/main/res/layout/activity_games_collection.xml
  Android/app/src/main/res/layout/game_items.xml
  Android/app/src/main/res/values/strings.xml
Labels: Frontend

#43 Basic Layout Navigation with Starting Fragments for 2 Activities
  Android/app/build.gradle
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/java/com/example/boardgamesocial/EventsFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/HomePostFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/LoginAndSignUpActivity.java
  Android/app/src/main/java/com/example/boardgamesocial/LoginFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainAppActivity.java
  Android/app/src/main/java/com/example/boardgamesocial/ProfileFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/SignUpFragment.java
  Android/app/src/main/res/layout/activity_home_post.xml
  Android/app/src/main/res/layout/activity_login_and_sign_up.xml
  Android/app/src/main/res/layout/activity_main_app.xml
  Android/app/src/main/res/layout/content_app.xml
  Android/app/src/main/res/layout/content_main_app.xml
  Android/app/src/main/res/layout/fragment_event.xml
  Android/app/src/main/res/layout/fragment_home_post.xml
  Android/app/src/main/res/layout/fragment_login.xml
  Android/app/src/main/res/layout/fragment_profile.xml
  Android/app/src/main/res/layout/fragment_sign_up.xml
  Android/app/src/main/res/navigation/nav_login_and_sign_up.xml
  Android/app/src/main/res/navigation/nav_main_app.xml
  Android/app/src/main/res/values-land/dimens.xml
  Android/app/src/main/res/values-w1240dp/dimens.xml
  Android/app/src/main/res/values-w600dp/dimens.xml
  Android/app/src/main/res/values/dimens.xml
  Android/app/src/main/res/values/themes.xml
Labels: Frontend

#44 main <-- Home post profile fragments
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/java/com/example/boardgamesocial/EventsFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/HomePostFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/LoginAndSignUpActivity.java
  Android/app/src/main/java/com/example/boardgamesocial/LoginFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainAppActivity.java
  Android/app/src/main/java/com/example/boardgamesocial/ProfileFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/SignUpFragment.java
  Android/app/src/main/res/drawable/circular.xml
  Android/app/src/main/res/drawable/ic_baseline_add_24.xml
  Android/app/src/main/res/drawable/ic_baseline_favorite_24.xml
  Android/app/src/main/res/drawable/ic_baseline_person_24.xml
  Android/app/src/main/res/drawable/show_circular_image.xml
  Android/app/src/main/res/layout/activity_home_post.xml
  Android/app/src/main/res/layout/activity_main_app.xml
  Android/app/src/main/res/layout/fragment_events.xml
  Android/app/src/main/res/layout/fragment_home_post.xml
  Android/app/src/main/res/layout/fragment_profile.xml
  Android/app/src/main/res/layout/item.xml
  Android/app/src/main/res/navigation/nav_main_app.xml
  Android/app/src/main/res/values/colors.xml
  Android/app/src/main/res/values/dimens.xml
  Android/app/src/main/res/values/strings.xml
Labels: Frontend

#45 Backend improvements
  Backend/Backend/urls.py
  Backend/BoardGameSocialAPI/models.py
  Backend/BoardGameSocialAPI/tests.py
  Backend/BoardGameSocialAPI/views.py
Labels: Backend

#46 Retrofit API
  Android/app/build.gradle
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/java/com/example/boardgamesocial/API/API.java
  Android/app/src/main/java/com/example/boardgamesocial/API/HeaderInterceptor.java
  Android/app/src/main/java/com/example/boardgamesocial/API/LoggingInterceptor.java
  Android/app/src/main/java/com/example/boardgamesocial/API/RetrofitClient.java
  Android/app/src/main/java/com/example/boardgamesocial/DataClasses/Comment.java
  Android/app/src/main/java/com/example/boardgamesocial/DataClasses/DataClass.java
  Android/app/src/main/java/com/example/boardgamesocial/DataClasses/Event.java
  Android/app/src/main/java/com/example/boardgamesocial/DataClasses/Game.java
  Android/app/src/main/java/com/example/boardgamesocial/DataClasses/HostedGame.java
  Android/app/src/main/java/com/example/boardgamesocial/DataClasses/Message.java
  Android/app/src/main/java/com/example/boardgamesocial/DataClasses/Post.java
  Android/app/src/main/java/com/example/boardgamesocial/DataClasses/Relationships/EventToUser.java
  Android/app/src/main/java/com/example/boardgamesocial/DataClasses/Relationships/GameToUser.java
  Android/app/src/main/java/com/example/boardgamesocial/DataClasses/Relationships/HostedGameToUser.java
  Android/app/src/main/java/com/example/boardgamesocial/DataClasses/Relationships/UserToUser.java
  Android/app/src/main/java/com/example/boardgamesocial/DataClasses/Review.java
  Android/app/src/main/java/com/example/boardgamesocial/DataClasses/Token.java
  Android/app/src/main/java/com/example/boardgamesocial/DataClasses/User.java
  Android/app/src/main/java/com/example/boardgamesocial/LoginAndSignUpActivity.java
  Android/app/src/main/java/com/example/boardgamesocial/MainActivity.java
  Android/app/src/test/java/android/util/Log.java
  Android/app/src/test/java/com/example/boardgamesocial/APITests/DBEndPointsTests.java
  Android/app/src/test/java/com/example/boardgamesocial/APITests/DBTestStage/ConsoleColor.java
  Android/app/src/test/java/com/example/boardgamesocial/APITests/DBTestStage/StageAction.java
  Android/app/src/test/java/com/example/boardgamesocial/APITests/DBTestStage/StageSettings.java
  Android/app/src/test/java/com/example/boardgamesocial/APITests/DBTestStage/TestStage.java
  Android/app/src/test/java/com/example/boardgamesocial/APITests/UserAuthTests.java
  Backend/BoardGameSocialAPI/view_manager/data_access_view.py
  Backend/BoardGameSocialAPI/views.py
Labels: Backend, Frontend

#47 Navigation Layout Fragrments
  Android/app/src/main/java/com/example/boardgamesocial/AddPostFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/ChatFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/EditProfileFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/EventAttendeesFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/FriendChatFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/GameCollectionFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/HostedGamesFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainActivity.java
  Android/app/src/main/java/com/example/boardgamesocial/SearchFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/SingleEventFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/SingleHostedGameFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/SinglePostFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/UserFriendsFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/UserProfileFragment.java
  Android/app/src/main/res/layout/fragment_add_post.xml
  Android/app/src/main/res/layout/fragment_chat.xml
  Android/app/src/main/res/layout/fragment_edit_profile.xml
  Android/app/src/main/res/layout/fragment_event_attendees.xml
  Android/app/src/main/res/layout/fragment_friend_chat.xml
  Android/app/src/main/res/layout/fragment_game_collection.xml
  Android/app/src/main/res/layout/fragment_hosted_games.xml
  Android/app/src/main/res/layout/fragment_search.xml
  Android/app/src/main/res/layout/fragment_single_event.xml
  Android/app/src/main/res/layout/fragment_single_hosted_game.xml
  Android/app/src/main/res/layout/fragment_single_post.xml
  Android/app/src/main/res/layout/fragment_user_friends.xml
  Android/app/src/main/res/layout/fragment_user_profile.xml
  Android/app/src/main/res/navigation/nav_main_app.xml
Labels: Frontend

#48 main <- Home post profile fragments
  Android/app/src/main/java/com/example/boardgamesocial/HomePostFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/LoginAndSignUpActivity.java
  Android/app/src/main/java/com/example/boardgamesocial/MainAppActivity.java
  Android/app/src/main/res/drawable/ic_baseline_event_24_blue_yonder.xml
  Android/app/src/main/res/drawable/ic_baseline_home_24_blue_yonder.xml
  Android/app/src/main/res/drawable/ic_baseline_logout_24_blue_yonder.xml
  Android/app/src/main/res/drawable/ic_baseline_person_24_blue_yonder.xml
  Android/app/src/main/res/drawable/ic_baseline_reorder_24_blue_yonder.xml
  Android/app/src/main/res/layout/activity_main_app.xml
  Android/app/src/main/res/layout/fragment_home_post.xml
  Android/app/src/main/res/layout/fragment_profile.xml
  Android/app/src/main/res/menu/navbar_options.xml
  Android/app/src/main/res/values/colors.xml
  Android/app/src/main/res/values/dimens.xml
  Android/app/src/main/res/values/strings.xml
  README.md
  docs/Board Game Social ERD.png
Labels: Frontend

#49 fixed typo on line 66 of MainAppActivity.java
  Android/app/src/main/java/com/example/boardgamesocial/MainAppActivity.java
Labels: bug, Frontend

#50 Login functionality
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/java/com/example/boardgamesocial/API/HeaderInterceptor.java
  Android/app/src/main/java/com/example/boardgamesocial/API/RetrofitClient.java
  Android/app/src/main/java/com/example/boardgamesocial/DataClasses/User.java
  Android/app/src/main/java/com/example/boardgamesocial/GamesCollectionActivity.java
  Android/app/src/main/java/com/example/boardgamesocial/HomePostActivity.java
  Android/app/src/main/java/com/example/boardgamesocial/LoginAndSignUpActivity.java
  Android/app/src/main/java/com/example/boardgamesocial/LoginFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/SignUpActivity.java
  Android/app/src/main/java/com/example/boardgamesocial/SignUpFragment.java
  Android/app/src/main/res/layout/activity_games_collection.xml
  Android/app/src/main/res/layout/activity_main.xml
  Android/app/src/main/res/layout/activity_sign_up.xml
  Android/app/src/main/res/layout/fragment_login.xml
  Android/app/src/main/res/layout/fragment_sign_up.xml
  Android/app/src/main/res/values/strings.xml
Labels: Frontend

#51 main <-- Home post profile fragments
  Android/app/src/main/java/com/example/boardgamesocial/HomePostFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainAppActivity.java
  Android/app/src/main/java/com/example/boardgamesocial/ProfileFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/RecycleAdapters/PostAdapter.java
  Android/app/src/main/res/layout/activity_main_app.xml
  Android/app/src/main/res/layout/fragment_add_post.xml
  Android/app/src/main/res/layout/fragment_edit_profile.xml
  Android/app/src/main/res/layout/fragment_events.xml
  Android/app/src/main/res/layout/fragment_game_collection.xml
  Android/app/src/main/res/layout/fragment_search.xml
  Android/app/src/main/res/values/strings.xml
Labels: Frontend

#52 Games collection
  Android/app/build.gradle
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/java/com/example/boardgamesocial/API/RetrofitClient.java
  Android/app/src/main/java/com/example/boardgamesocial/AddGameFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/DataClasses/Commons/Constants.java
  Android/app/src/main/java/com/example/boardgamesocial/DataClasses/Commons/Utils.java
  Android/app/src/main/java/com/example/boardgamesocial/GameCollectionFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/GamesCollectionActivity.java
  Android/app/src/main/java/com/example/boardgamesocial/HomePostActivity.java
  Android/app/src/main/java/com/example/boardgamesocial/LoginFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainActivity.java
  Android/app/src/main/java/com/example/boardgamesocial/RecycleAdapters/GameAdapter.java
  Android/app/src/main/java/com/example/boardgamesocial/SignUpActivity.java
  Android/app/src/main/res/drawable/ic_image_placeholder.xml
  Android/app/src/main/res/drawable/ic_launcher_background.xml
  Android/app/src/main/res/layout/activity_games_collection.xml
  Android/app/src/main/res/layout/activity_home_post.xml
  Android/app/src/main/res/layout/activity_main.xml
  Android/app/src/main/res/layout/activity_sign_up.xml
  Android/app/src/main/res/layout/fragment_add_game.xml
  Android/app/src/main/res/layout/fragment_game_collection.xml
  Android/app/src/main/res/layout/fragment_home_post.xml
  Android/app/src/main/res/layout/game_items.xml
  Android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Android/app/src/main/res/values/strings.xml
Labels: Frontend

#53 Docker updated
  Android/app/src/main/java/com/example/boardgamesocial/API/API.java
  Backend/Backend/settings.py
  Backend/Backend/urls.py
  backend/Dockerfile
Labels: bug, DevOps

#61 Data class view containers
  Android/app/src/main/java/com/example/boardgamesocial/API/RetrofitClient.java
  Android/app/src/main/java/com/example/boardgamesocial/DataClasses/DataClass.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/DataClsAdapter.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/ViewHolders/DataClsVH.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/ViewHolders/EventVH.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/ViewHolders/GameVH.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/ViewHolders/PostVH.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/DataClsVM.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/AddEventFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/EventsFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/GameCollectionFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/HomePostFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/SingleEventFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/SinglePostFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/UserGamesFragment.java
Labels: Frontend

#62 added more ViewHolder Templates
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/ViewHolders/CommentVH.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/ViewHolders/HostedGameVH.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/ViewHolders/MessageVH.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/ViewHolders/RelationshipVH/EventToUserVH.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/ViewHolders/RelationshipVH/GameToUserVH.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/ViewHolders/RelationshipVH/HostedGameToUserVH.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/ViewHolders/RelationshipVH/UserToUserVH.java
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/ViewHolders/ReviewVH.java
Labels: Frontend

#63 Readme update
  README.md
Labels: documentation

#65 New games collection
  Android/app/src/main/java/com/example/boardgamesocial/DataViews/Adapters/DataClsAdapter.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/AddGameFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/EventsFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/HostedGamesFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/SingleEventFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/SingleHostedGameFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/MainAppActivity.java
  Android/app/src/main/res/layout/fragment_add_event.xml
  Android/app/src/main/res/layout/fragment_add_game.xml
  Android/app/src/main/res/layout/fragment_hosted_games.xml
  Android/app/src/main/res/layout/fragment_single_hosted_game.xml
  Android/app/src/main/res/navigation/nav_main_app.xml
  Android/app/src/main/res/values/strings.xml
Labels: Frontend

#64 BottomAppBar appearance and Profile, AddPost fragments
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/AddPostFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/HomePostFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/Fragments/ProfileFragment.java
  Android/app/src/main/java/com/example/boardgamesocial/MainApp/MainAppActivity.java
  Android/app/src/main/res/layout/fragment_add_post.xml
  Android/app/src/main/res/layout/fragment_profile.xml
  Android/app/src/main/res/navigation/nav_main_app.xml
  Android/app/src/main/res/values/dimens.xml
  Android/app/src/main/res/values/strings.xml
Labels: question, Frontend
